version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: faq_db_container
    environment:
      POSTGRES_USER: faq_app
      POSTGRES_PASSWORD: sua_senha_segura
      POSTGRES_DB: faq_db
    volumes:
      - faq-postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - faq-net

  app:
    build: .
    container_name: faq_app_container
    environment:
      DATABASE_URL: postgres://faq_app:sua_senha_segura@db:5432/faq_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - faq-net

  prometheus:
    image: prom/prometheus:latest
    container_name: faq_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - faq-prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - faq-net

  grafana:
    image: grafana/grafana:latest
    container_name: faq_grafana
    volumes:
      - faq-grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true" # Para acesso mais fácil em desenvolvimento
    depends_on:
      - prometheus
    networks:
      - faq-net

  postgres-exporter:
    image: prom/postgres-exporter:latest
    container_name: faq_postgres_exporter
    environment:
      DATA_SOURCE_NAME: postgres://faq_app:sua_senha_segura@db:5432/faq_db
    ports:
      - "9187:9187"
    networks:
      - faq-net
    depends_on:
      - db

networks:
  faq-net:
    driver: bridge

volumes:
  faq-postgres-data:
  faq-prometheus-data:
  faq-grafana-data:
