global:
  scrape_interval:     5s

scrape_configs:
  - job_name: 'app'
    metrics_path: '/metrics' # Defina o caminho das métricas na sua aplicação Node.JS
    static_configs:
      - targets: ['app:3000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
