# Use a imagem oficial do Grafana como base
FROM grafana/grafana:latest

# Copie arquivos de configuração personalizados, se necessário (opcional)
# COPY custom-config.ini /etc/grafana/grafana.ini

# Exponha a porta padrão do Grafana
EXPOSE 3000

# Comando para iniciar o Grafana
CMD ["/run.sh"]